---

name: build

on: [push]

concurrency:
  group: ${{ github.workflow }}--${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:

    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: |
          2.7

    - run: python3 -m pip install tox

    - run: python3 -m tox run

    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: log-${{ matrix.os }}
        path: |
          .tox/py*/log
          .tox/py*/tmp/testenv
        if-no-files-found: ignore
